
const GRID_W=200,GRID_H=200,CELL_CM=0.1,DOMAIN_W=GRID_W*CELL_CM,DOMAIN_H=GRID_H*CELL_CM,MAX_TR=360,N_BINS=80,TWO_PI=Math.PI*2;
const MAT={VACUUM:0,AIR:1,WATER:2,IRON:3,LEAD:4,U235:5,CONCRETE:6};
const MAT_NAMES=['Vuoto','Aria','Acqua','Ferro','Piombo','U-235','Calcestruzzo'];
const MAT_COLORS=['#30485d','#587892','#78d7ff','#c9d3dc','#b596d3','#ff8f63','#d4bf98'];
const MATERIALS=[{density:0,Z:0,A:0,I_eV:0,sig_s:0,sig_c:0,sig_f:0,nu:0,Ef:0},{density:1.293e-3,Z:7.36,A:14.5,I_eV:85.7,sig_s:10,sig_c:1,sig_f:0,nu:0,Ef:0},{density:1,Z:7.22,A:11.9,I_eV:75,sig_s:20,sig_c:.3,sig_f:0,nu:0,Ef:0},{density:7.874,Z:26,A:55.85,I_eV:286,sig_s:2.5,sig_c:2.6,sig_f:0,nu:0,Ef:0},{density:11.35,Z:82,A:207.2,I_eV:823,sig_s:11,sig_c:.17,sig_f:0,nu:0,Ef:0},{density:18.95,Z:92,A:235,I_eV:890,sig_s:4,sig_c:99,sig_f:584,nu:2.43,Ef:200},{density:2.3,Z:11,A:22,I_eV:135.7,sig_s:3,sig_c:.1,sig_f:0,nu:0,Ef:0}];
let matGrid=new Uint8Array(GRID_W*GRID_H),fluenceN=new Float32Array(GRID_W*GRID_H),fluenceP=new Float32Array(GRID_W*GRID_H),fluenceE=new Float32Array(GRID_W*GRID_H),doseMap=new Float32Array(GRID_W*GRID_H),specNeut=new Float32Array(N_BINS),specPhot=new Float32Array(N_BINS);
let totalHist=0,totalFiss=0,totalCapt=0,totalScat=0,fissHistory=[],captHistory=[];
let srcX=6,srcY=10,srcE=2,srcType=0,srcIso=1,srcDx=1,srcDy=0,wasmReady=false,wasmAPI=null,wasmPtrs=null,frameTrackBuf=[],activePreset='filters',sceneLabels=[];
let trackFade=.947,showTrackMode='all',running=true,lastT=0,fps=0,fpsCount=0,fpsT=0,paintMat=MAT.WATER,isPainting=false,brushSize=3,pendingGeometryReset=false,lastChartUpdate=0,lastStatsUpdate=0;
const cMain=document.getElementById('main'),cTrack=document.getElementById('track'),cOverlay=document.getElementById('overlay'),ctxMain=cMain.getContext('2d'),ctxTrack=cTrack.getContext('2d'),ctxOvr=cOverlay.getContext('2d'),tooltip=document.getElementById('tooltip');
const materialLayer=document.createElement('canvas'),materialCtx=materialLayer.getContext('2d'),outlineLayer=document.createElement('canvas'),outlineCtx=outlineLayer.getContext('2d'),heatLayer=document.createElement('canvas'),heatCtx=heatLayer.getContext('2d');let materialDirty=true,CW=0,CH=0,scaleX=1,scaleY=1;
function resizeFooterCharts(){['chart-neut','chart-phot','chart-dose','chart-hist'].forEach(id=>{const c=document.getElementById(id),r=c.parentElement.getBoundingClientRect();c.width=Math.max(120,Math.floor(r.width-4));c.height=118})}
function resizeCanvases(){const r=document.getElementById('center').getBoundingClientRect();CW=Math.max(160,Math.floor(r.width));CH=Math.max(160,Math.floor(r.height));[cMain,cTrack,cOverlay].forEach(c=>{c.width=CW;c.height=CH});[ctxMain,ctxTrack,ctxOvr].forEach(ctx=>ctx.imageSmoothingEnabled=false);materialLayer.width=GRID_W;materialLayer.height=GRID_H;outlineLayer.width=GRID_W;outlineLayer.height=GRID_H;heatLayer.width=GRID_W;heatLayer.height=GRID_H;[materialCtx,outlineCtx,heatCtx].forEach(ctx=>ctx.imageSmoothingEnabled=false);scaleX=CW/DOMAIN_W;scaleY=CH/DOMAIN_H;materialDirty=true;renderFrame()}
function getHeaps(){const heapU8=Module.HEAPU8||(typeof HEAPU8!=='undefined'?HEAPU8:null),heapF32=Module.HEAPF32||(typeof HEAPF32!=='undefined'?HEAPF32:null);if(!heapU8||!heapF32)throw new Error('Heap WASM non accessibile');return{heapU8,heapF32}}
function refreshWasmViews(){if(!wasmReady||!wasmPtrs)return;const n=GRID_W*GRID_H,{heapU8,heapF32}=getHeaps();matGrid=new Uint8Array(heapU8.buffer,wasmPtrs.matGrid,n);fluenceN=new Float32Array(heapF32.buffer,wasmPtrs.fluenceN,n);fluenceP=new Float32Array(heapF32.buffer,wasmPtrs.fluenceP,n);fluenceE=new Float32Array(heapF32.buffer,wasmPtrs.fluenceE,n);doseMap=new Float32Array(heapF32.buffer,wasmPtrs.dose,n);specNeut=new Float32Array(heapF32.buffer,wasmPtrs.specNeut,N_BINS);specPhot=new Float32Array(heapF32.buffer,wasmPtrs.specPhot,N_BINS)}
function applySourceToWasm(){if(wasmReady&&wasmAPI&&wasmAPI.setSource)wasmAPI.setSource(srcX,srcY,srcE,srcType,srcIso,srcDx,srcDy)}
function getMaterialPhysics(mid,e){if(!wasmReady||!wasmAPI||!wasmAPI.queryMaterial)return null;const ptr=wasmAPI.queryMaterial(mid,e),{heapF32}=getHeaps();return Array.from(new Float32Array(heapF32.buffer,ptr,9))}
function resetAccumulators(){if(wasmReady&&wasmAPI&&wasmAPI.resetTallies){wasmAPI.resetTallies();refreshWasmViews();applySourceToWasm()}else{fluenceN.fill(0);fluenceP.fill(0);fluenceE.fill(0);doseMap.fill(0);specNeut.fill(0);specPhot.fill(0)}totalHist=0;totalFiss=0;totalCapt=0;totalScat=0;frameTrackBuf.length=0;fissHistory=[];captHistory=[];lastChartUpdate=0;lastStatsUpdate=0}
function commitGeometryReset(){if(!pendingGeometryReset)return;pendingGeometryReset=false;resetAccumulators();renderFrame()}
function setPresetNote(text){const el=document.getElementById('preset-note');if(el)el.textContent=text}
function loadPreset(name){
activePreset=name;sceneLabels=[];matGrid.fill(MAT.AIR);
if(name==='filters'){
for(let y=36;y<164;y++)for(let x=38;x<42;x++)matGrid[y*GRID_W+x]=MAT.LEAD;
for(let y=30;y<170;y++)for(let x=78;x<90;x++)matGrid[y*GRID_W+x]=MAT.IRON;
for(let y=24;y<176;y++)for(let x=128;x<164;x++)matGrid[y*GRID_W+x]=MAT.WATER;
sceneLabels=[{x:4.0,y:3.2,text:'Pb: gamma',color:'#ffd257'},{x:8.4,y:3.2,text:'Fe: e-',color:'#68caff'},{x:14.6,y:3.2,text:'H2O: n',color:'#8dff67'}];
srcX=1.5;srcY=10;srcE=2.5;srcType=1;srcIso=0;srcDx=1;srcDy=0;
document.getElementById('src-type').value='1';document.getElementById('src-energy').value='2.5';document.getElementById('src-mode').value='0';document.getElementById('n-primary').value='18';document.getElementById('view-mode').value='material';document.getElementById('track-mode').value='all';
setPresetNote('Demo filtri: piombo attenua soprattutto i fotoni, il ferro accorcia molto le tracce degli elettroni, l acqua rallenta e diffonde i neutroni.');
}else if(name==='shield'){
for(let y=30;y<170;y++)for(let x=80;x<100;x++)matGrid[y*GRID_W+x]=MAT.LEAD;
for(let y=30;y<170;y++)for(let x=110;x<130;x++)matGrid[y*GRID_W+x]=MAT.IRON;
for(let y=30;y<170;y++)for(let x=140;x<170;x++)matGrid[y*GRID_W+x]=MAT.CONCRETE;
srcX=2;srcY=10;srcE=1.25;srcType=1;srcIso=0;srcDx=1;srcDy=0;
document.getElementById('src-type').value='1';document.getElementById('src-energy').value='1.25';document.getElementById('src-mode').value='0';document.getElementById('view-mode').value='dose';
setPresetNote('Schermatura multistrato compatta per un fascio di fotoni direzionale.');
}else{
matGrid.fill(MAT.WATER);
for(let y=0;y<GRID_H;y++)for(let x=0;x<GRID_W;x++){const dx=x-60,dy=y-100;if(dx*dx+dy*dy<=225)matGrid[y*GRID_W+x]=MAT.U235}
for(let y=60;y<140;y++)for(let x=120;x<160;x++)matGrid[y*GRID_W+x]=MAT.LEAD;
for(let y=80;y<120;y++)for(let x=160;x<185;x++)matGrid[y*GRID_W+x]=MAT.CONCRETE;
srcX=60*CELL_CM;srcY=100*CELL_CM;srcE=2;srcType=0;srcIso=1;srcDx=1;srcDy=0;
document.getElementById('src-type').value='0';document.getElementById('src-energy').value='2';document.getElementById('src-mode').value='1';document.getElementById('view-mode').value='material';
setPresetNote('Preset reattore: nocciolo di U-235 immerso in acqua con schermi a valle.');
}
updateUI();materialDirty=true;resetAccumulators();renderFrame()
}
function clearGeometry(){activePreset='custom';sceneLabels=[];setPresetNote('Geometria pulita. Disegna materiali e usa la sorgente per creare una scena personalizzata.');matGrid.fill(MAT.AIR);materialDirty=true;resetAccumulators();renderFrame()}
function heatColor(t){const x=Math.max(0,Math.min(1,t)),s=[[0,[0,0,20]],[.18,[0,0,180]],[.35,[0,200,255]],[.55,[0,255,100]],[.72,[255,255,0]],[.86,[255,100,0]],[1,[255,255,255]]];for(let i=0;i<s.length-1;i++)if(x<=s[i+1][0]){const f=(x-s[i][0])/(s[i+1][0]-s[i][0]),a=s[i][1],b=s[i+1][1];return[Math.round(a[0]+(b[0]-a[0])*f),Math.round(a[1]+(b[1]-a[1])*f),Math.round(a[2]+(b[2]-a[2])*f)]}return[255,255,255]}
function renderMaterial(){if(materialDirty){const img=materialCtx.createImageData(GRID_W,GRID_H),d=img.data;for(let y=0;y<GRID_H;y++)for(let x=0;x<GRID_W;x++){const hex=MAT_COLORS[matGrid[y*GRID_W+x]]||'#30485d',i4=(y*GRID_W+x)*4;d[i4]=parseInt(hex.slice(1,3),16);d[i4+1]=parseInt(hex.slice(3,5),16);d[i4+2]=parseInt(hex.slice(5,7),16);d[i4+3]=255}materialCtx.putImageData(img,0,0);outlineCtx.clearRect(0,0,GRID_W,GRID_H);outlineCtx.beginPath();for(let y=0;y<GRID_H;y++)for(let x=0;x<GRID_W;x++){const here=matGrid[y*GRID_W+x];if(x<GRID_W-1&&matGrid[y*GRID_W+x+1]!==here){outlineCtx.moveTo(x+1,y);outlineCtx.lineTo(x+1,y+1)}if(y<GRID_H-1&&matGrid[(y+1)*GRID_W+x]!==here){outlineCtx.moveTo(x,y+1);outlineCtx.lineTo(x+1,y+1)}}outlineCtx.strokeStyle='rgba(246,250,255,.52)';outlineCtx.lineWidth=1;outlineCtx.stroke();materialDirty=false}ctxMain.clearRect(0,0,CW,CH);ctxMain.fillStyle='#294156';ctxMain.fillRect(0,0,CW,CH);ctxMain.globalAlpha=.98;ctxMain.drawImage(materialLayer,0,0,CW,CH);ctxMain.globalAlpha=.78;ctxMain.drawImage(outlineLayer,0,0,CW,CH);ctxMain.globalAlpha=1}
function renderHeatmap(buf,scale){let maxV=0;for(let i=0;i<buf.length;i++)if(buf[i]>maxV)maxV=buf[i];if(maxV<=0)return;const img=heatCtx.createImageData(GRID_W,GRID_H),d=img.data;for(let y=0;y<GRID_H;y++)for(let x=0;x<GRID_W;x++){const v=buf[y*GRID_W+x];if(v<=0)continue;const col=heatColor(Math.min(1,Math.log10(1+v*scale/maxV*9)*scale)),i4=(y*GRID_W+x)*4;d[i4]=col[0];d[i4+1]=col[1];d[i4+2]=col[2];d[i4+3]=180}heatCtx.putImageData(img,0,0);ctxMain.drawImage(heatLayer,0,0,CW,CH)}
function renderTracks(){ctxTrack.save();ctxTrack.globalCompositeOperation='destination-out';ctxTrack.fillStyle=`rgba(0,0,0,${Math.max(.01,1-trackFade)})`;ctxTrack.fillRect(0,0,CW,CH);ctxTrack.restore();const colors=['#8dff67','#ffd257','#68caff','#ff98d1'],w=[1.1,.95,.72,.72],a=[.42,.37,.28,.24];for(const trk of frameTrackBuf){if(showTrackMode==='none')continue;if(showTrackMode==='neutron'&&trk.type!==0)continue;if(showTrackMode==='photon'&&trk.type!==1)continue;if(showTrackMode==='electron'&&trk.type!==2&&trk.type!==3)continue;if(trk.pts.length<2)continue;ctxTrack.strokeStyle=colors[trk.type]||'#fff';ctxTrack.lineWidth=w[trk.type]||.8;ctxTrack.globalAlpha=a[trk.type]||.28;ctxTrack.shadowBlur=1.5;ctxTrack.shadowColor=colors[trk.type]||'#fff';ctxTrack.beginPath();ctxTrack.moveTo(trk.pts[0].x*scaleX,trk.pts[0].y*scaleY);for(let i=1;i<trk.pts.length;i++)ctxTrack.lineTo(trk.pts[i].x*scaleX,trk.pts[i].y*scaleY);ctxTrack.stroke()}ctxTrack.globalAlpha=1;ctxTrack.shadowBlur=0}
function renderGridOverlay(){ctxOvr.strokeStyle='rgba(120,160,190,.18)';ctxOvr.lineWidth=.5;for(let x=0;x<=GRID_W;x+=10){ctxOvr.beginPath();ctxOvr.moveTo(x*CELL_CM*scaleX,0);ctxOvr.lineTo(x*CELL_CM*scaleX,CH);ctxOvr.stroke()}for(let y=0;y<=GRID_H;y+=10){ctxOvr.beginPath();ctxOvr.moveTo(0,y*CELL_CM*scaleY);ctxOvr.lineTo(CW,y*CELL_CM*scaleY);ctxOvr.stroke()}}
function renderSceneLabels(){if(!sceneLabels.length)return;ctxOvr.save();ctxOvr.font='12px Segoe UI,sans-serif';ctxOvr.textAlign='center';ctxOvr.textBaseline='bottom';for(const l of sceneLabels){const x=l.x*CELL_CM*scaleX,y=l.y*CELL_CM*scaleY;ctxOvr.fillStyle='rgba(8,16,24,.82)';ctxOvr.fillRect(x-52,y-20,104,18);ctxOvr.strokeStyle=l.color||'rgba(124,226,255,.7)';ctxOvr.strokeRect(x-52,y-20,104,18);ctxOvr.fillStyle=l.color||'#dce9f3';ctxOvr.fillText(l.text,x,y-6)}ctxOvr.restore()}
function renderSource(){ctxOvr.clearRect(0,0,CW,CH);const sx=srcX*scaleX,sy=srcY*scaleY;ctxOvr.fillStyle='rgba(255,255,255,.9)';ctxOvr.beginPath();ctxOvr.arc(sx,sy,5.5,0,TWO_PI);ctxOvr.fill();ctxOvr.strokeStyle='rgba(255,255,255,.45)';ctxOvr.lineWidth=1;ctxOvr.beginPath();ctxOvr.arc(sx,sy,9,0,TWO_PI);ctxOvr.stroke();ctxOvr.fillStyle='rgba(255,255,255,.72)';ctxOvr.font='12px Consolas';ctxOvr.fillText(['n','g','e-'][srcType]||'?',sx+11,sy-4);ctxOvr.fillText(srcE.toFixed(2)+' MeV',sx+11,sy+10);if(document.getElementById('show-grid').checked)renderGridOverlay();renderSceneLabels()}
function renderFrame(){renderMaterial();const v=document.getElementById('view-mode').value;if(v!=='material'){const s=parseFloat(document.getElementById('dose-scale').value),buf=v==='dose'?doseMap:v==='fluence_n'?fluenceN:v==='fluence_p'?fluenceP:fluenceE;renderHeatmap(buf,s)}renderTracks();renderSource()}
function drawBar(canvas,data,color){const ctx=canvas.getContext('2d');ctx.clearRect(0,0,canvas.width,canvas.height);let max=0;for(let i=0;i<data.length;i++)if(data[i]>max)max=data[i];if(max<=0)return;const bw=canvas.width/data.length;ctx.fillStyle=color;for(let i=0;i<data.length;i++){if(data[i]<=0)continue;const v=Math.log10(1+data[i])/Math.log10(1+max);ctx.fillRect(i*bw,canvas.height*(1-v),Math.max(1,bw-1),canvas.height*v)}}
function drawLine(canvas,d1,d2,c1,c2){const ctx=canvas.getContext('2d');ctx.clearRect(0,0,canvas.width,canvas.height);const max=Math.max(1,...d1,...d2);[[d1,c1],[d2,c2]].forEach(([d,c])=>{if(d.length<2)return;ctx.strokeStyle=c;ctx.lineWidth=1.8;ctx.beginPath();for(let i=0;i<d.length;i++){const x=i/Math.max(1,d.length-1)*canvas.width,y=canvas.height*(1-d[i]/max);if(i===0)ctx.moveTo(x,y);else ctx.lineTo(x,y)}ctx.stroke()})}
function drawDose(canvas){const ctx=canvas.getContext('2d');ctx.clearRect(0,0,canvas.width,canvas.height);const p=new Float32Array(GRID_W);for(let y=0;y<GRID_H;y++)for(let x=0;x<GRID_W;x++)p[x]+=doseMap[y*GRID_W+x];let max=0;for(let x=0;x<GRID_W;x++)if(p[x]>max)max=p[x];if(max<=0)return;const bw=canvas.width/GRID_W;ctx.fillStyle='rgba(255,120,60,.75)';for(let x=0;x<GRID_W;x++){const v=Math.log10(1+p[x])/Math.log10(1+max);ctx.fillRect(x*bw,canvas.height*(1-v),bw,canvas.height*v)}}
function updateCharts(){drawBar(document.getElementById('chart-neut'),specNeut,'rgba(141,255,103,.72)');drawBar(document.getElementById('chart-phot'),specPhot,'rgba(255,210,87,.72)');drawDose(document.getElementById('chart-dose'));drawLine(document.getElementById('chart-hist'),fissHistory,captHistory,'#ff7c3f','#ffe06b')}
function updateStats(){[['hist',totalHist],['fiss',totalFiss],['capt',totalCapt],['scat',totalScat]].forEach(([k,v])=>{document.getElementById('hd-'+k).textContent=Number(v).toLocaleString('it');document.getElementById('stat-'+k).textContent=Number(v).toLocaleString('it')});document.getElementById('stat-keff').textContent=(totalHist>0?(totalFiss*2.43/totalHist):0).toFixed(3);let maxDose=0;for(let i=0;i<doseMap.length;i++)if(doseMap[i]>maxDose)maxDose=doseMap[i];document.getElementById('stat-dose').textContent=maxDose.toExponential(2)}
function getPos(e){const r=cMain.getBoundingClientRect();return[Math.floor((e.clientX-r.left)/scaleX/CELL_CM),Math.floor((e.clientY-r.top)/scaleY/CELL_CM)]}
function paintCell(e){const [cx,cy]=getPos(e);for(let dy=-brushSize;dy<=brushSize;dy++)for(let dx=-brushSize;dx<=brushSize;dx++){if(dx*dx+dy*dy>brushSize*brushSize)continue;const nx=cx+dx,ny=cy+dy;if(nx>=0&&nx<GRID_W&&ny>=0&&ny<GRID_H)matGrid[ny*GRID_W+nx]=paintMat}materialDirty=true;pendingGeometryReset=true;if(!running)renderFrame()}
function showTooltip(e){const [cx,cy]=getPos(e);if(cx<0||cx>=GRID_W||cy<0||cy>=GRID_H){tooltip.style.display='none';return}const i=cy*GRID_W+cx;tooltip.style.display='block';tooltip.style.left=(e.offsetX+14)+'px';tooltip.style.top=(e.offsetY-10)+'px';tooltip.innerHTML=MAT_NAMES[matGrid[i]]+'<br>Dose: '+doseMap[i].toExponential(2)+' Gy<br>Phi_n='+fluenceN[i].toFixed(1)+' Phi_g='+fluenceP[i].toFixed(1)+' Phi_e='+fluenceE[i].toFixed(1)}
function showXS(e){const [cx,cy]=getPos(e);if(cx<0||cx>=GRID_W||cy<0||cy>=GRID_H)return;const mid=matGrid[cy*GRID_W+cx],q=getMaterialPhysics(mid,srcE);if(!q)return;const m=MATERIALS[mid];document.getElementById('xs-display').innerHTML='<b>'+MAT_NAMES[mid]+'</b><br>rho = '+m.density.toFixed(3)+' g/cm^3<br>Sigma_s = '+q[0].toExponential(3)+' cm^-1<br>Sigma_c = '+q[1].toExponential(3)+' cm^-1<br>Sigma_f = '+q[2].toExponential(3)+' cm^-1<br>mu_pe = '+q[4].toExponential(3)+' cm^-1<br>mu_c = '+q[5].toExponential(3)+' cm^-1<br>mu_pp = '+q[6].toExponential(3)+' cm^-1<br>-dE/dx = '+q[8].toFixed(4)+' MeV/cm';document.getElementById('mat-info').innerHTML='Z_eff = '+m.Z+' | A = '+m.A+'<br>I = '+m.I_eV+' eV<br>sigma_s(1MeV) = '+m.sig_s+' barn<br>sigma_c(th) = '+m.sig_c+' barn<br>sigma_f(th) = '+m.sig_f+' barn<br>'+(m.nu?('nu = '+m.nu+' | E_f = '+m.Ef+' MeV'):'')}
function buildPalette(){const pal=document.getElementById('mat-palette');pal.innerHTML='';MAT_NAMES.forEach((name,i)=>{const btn=document.createElement('div');btn.className='mat'+(i===paintMat?' on':'');btn.innerHTML='<div class="sw" style="background:'+MAT_COLORS[i]+'"></div>'+name;btn.onclick=()=>{paintMat=i;document.querySelectorAll('.mat').forEach(n=>n.classList.remove('on'));btn.classList.add('on')};pal.appendChild(btn)})}
function updateUI(){srcE=parseFloat(document.getElementById('src-energy').value);srcType=parseInt(document.getElementById('src-type').value,10);srcIso=parseInt(document.getElementById('src-mode').value,10);brushSize=parseInt(document.getElementById('brush-size').value,10);trackFade=parseFloat(document.getElementById('track-fade').value);showTrackMode=document.getElementById('track-mode').value;document.getElementById('src-energy-val').textContent=srcE.toFixed(2);document.getElementById('n-primary-val').textContent=document.getElementById('n-primary').value;document.getElementById('dose-scale-val').textContent=parseFloat(document.getElementById('dose-scale').value).toFixed(1)+'x';document.getElementById('track-fade-val').textContent=trackFade.toFixed(3);const d=document.getElementById('brush-dot'),px=Math.min(34,brushSize*3);d.style.width=px+'px';d.style.height=px+'px';applySourceToWasm()}
async function tryLoadWASM(){const dot=document.getElementById('status-dot'),label=document.getElementById('status-label'),xs=document.getElementById('xs-display');label.textContent='CARICAMENTO WASM';xs.textContent='Caricamento modulo in corso...';return new Promise((resolve,reject)=>{let settled=false,timeoutId=null;const finish=(ok,val)=>{if(settled)return;settled=true;if(timeoutId!==null)clearTimeout(timeoutId);ok?resolve(val):reject(val)};window.Module={locateFile(p){return p},onRuntimeInitialized(){try{overrideWithWASM();label.textContent=running?'IN ESECUZIONE':'IN PAUSA';xs.textContent='WASM pronto. Passa sul materiale per vedere le sezioni d\'urto.';finish(true)}catch(err){finish(false,err)}},onAbort(reason){finish(false,new Error(String(reason||'Abort del modulo WASM')))},printErr(text){if(text)console.error(text)}};timeoutId=setTimeout(()=>finish(false,new Error('Timeout durante l\'inizializzazione del modulo WASM')),12000);const s=document.createElement('script');s.src='transport.js';s.async=true;s.dataset.transportWasm='1';s.onerror=()=>{dot.className='paused';label.textContent='WASM NON DISPONIBILE';running=false;finish(false,new Error('transport.js non trovato'))};document.head.appendChild(s)}).catch(err=>{console.error(err);dot.className='paused';label.textContent='ERRORE WASM';running=false;document.getElementById('btn-play').textContent='Avvia';xs.innerHTML='<span style="color:#ffcf59">Modulo WASM non caricato.</span><br>'+err.message+'<br>Rigenera transport.js.'})}
function overrideWithWASM(){wasmAPI={init:Module.cwrap('sim_init',null,[]),step:Module.cwrap('sim_step','number',['number']),setSource:Module.cwrap('set_source',null,['number','number','number','number','number','number','number']),resetTallies:Module.cwrap('reset_tallies',null,[]),getFluenceN:Module.cwrap('get_fluence_n','number',[]),getFluenceP:Module.cwrap('get_fluence_p','number',[]),getFluenceE:Module.cwrap('get_fluence_e','number',[]),getDose:Module.cwrap('get_dose','number',[]),getMatGrid:Module.cwrap('get_mat_grid','number',[]),getSpecNeut:Module.cwrap('get_spec_neut','number',[]),getSpecPhot:Module.cwrap('get_spec_phot','number',[]),getTracks:Module.cwrap('get_tracks_buffer','number',[]),getTrackCount:Module.cwrap('get_track_count','number',[]),getTrackStride:Module.cwrap('get_track_stride','number',[]),getHistories:Module.cwrap('get_total_histories','number',[]),getFissions:Module.cwrap('get_total_fissions','number',[]),getCaptures:Module.cwrap('get_total_captures','number',[]),getScatterings:Module.cwrap('get_total_scatterings','number',[]),queryMaterial:Module.cwrap('query_material_response','number',['number','number'])};const local=Uint8Array.from(matGrid);wasmAPI.init();wasmPtrs={matGrid:wasmAPI.getMatGrid(),fluenceN:wasmAPI.getFluenceN(),fluenceP:wasmAPI.getFluenceP(),fluenceE:wasmAPI.getFluenceE(),dose:wasmAPI.getDose(),specNeut:wasmAPI.getSpecNeut(),specPhot:wasmAPI.getSpecPhot()};wasmReady=true;refreshWasmViews();matGrid.set(local);materialDirty=true;applySourceToWasm();window.simStep=n=>{const{heapF32}=getHeaps();applySourceToWasm();wasmAPI.step(n);refreshWasmViews();totalHist=wasmAPI.getHistories();totalFiss=wasmAPI.getFissions();totalCapt=wasmAPI.getCaptures();totalScat=wasmAPI.getScatterings();frameTrackBuf.length=0;const stride=wasmAPI.getTrackStride(),nTr=Math.min(wasmAPI.getTrackCount(),MAX_TR),arr=new Float32Array(heapF32.buffer,wasmAPI.getTracks(),nTr*stride);for(let i=0;i<nTr;i++){const base=i*stride,type=Math.round(arr[base]),npts=Math.round(arr[base+1]),pts=[];for(let j=0;j<npts;j++)pts.push({x:arr[base+2+j*3],y:arr[base+3+j*3],e:arr[base+4+j*3]});frameTrackBuf.push({type,pts})}fissHistory.push(totalFiss);captHistory.push(totalCapt);if(fissHistory.length>200){fissHistory.shift();captHistory.shift()}};resetAccumulators();matGrid.set(local);materialDirty=true;renderFrame();updateStats();updateCharts()}
function toggleRun(){running=!running;document.getElementById('btn-play').textContent=running?'Pausa':'Avvia';document.getElementById('status-dot').className=running?'':'paused';document.getElementById('status-label').textContent=running?'IN ESECUZIONE':'IN PAUSA'}
function resetSim(){resetAccumulators();ctxTrack.clearRect(0,0,CW,CH);renderFrame()}
function loop(ts){requestAnimationFrame(loop);if(!running||!wasmReady)return;const dt=ts-lastT;lastT=ts;fpsCount++;if(ts-fpsT>500){fps=Math.round(fpsCount*1000/Math.max(1,ts-fpsT));fpsT=ts;fpsCount=0;document.getElementById('hd-fps').textContent=String(fps)}const n=parseInt(document.getElementById('n-primary').value,10)||1;simStep(n);renderFrame();if(ts-lastChartUpdate>220){updateCharts();lastChartUpdate=ts}if(ts-lastStatsUpdate>160){updateStats();lastStatsUpdate=ts}}
cMain.addEventListener('mousedown',e=>{if(e.button===2){const r=cMain.getBoundingClientRect();srcX=(e.clientX-r.left)/scaleX;srcY=(e.clientY-r.top)/scaleY;applySourceToWasm();renderFrame();return}isPainting=true;paintCell(e)});cMain.addEventListener('mousemove',e=>{if(isPainting)paintCell(e);showTooltip(e);showXS(e)});cMain.addEventListener('mouseup',()=>{isPainting=false;commitGeometryReset()});cMain.addEventListener('mouseleave',()=>{isPainting=false;tooltip.style.display='none';commitGeometryReset()});cMain.addEventListener('contextmenu',e=>e.preventDefault());['src-energy','n-primary','track-fade','dose-scale','track-mode','src-type','src-mode','brush-size','view-mode','show-grid'].forEach(id=>document.getElementById(id).addEventListener('input',updateUI));window.addEventListener('load',()=>{resizeCanvases();resizeFooterCharts();buildPalette();loadPreset('filters');updateUI();tryLoadWASM();requestAnimationFrame(loop)});window.addEventListener('resize',()=>{resizeCanvases();resizeFooterCharts()});

